### ISSUE TITLE
LoadError on rspec_matcher require

### ISSUE THREAD

**Issue by rhymes** [perfectline/validates_url#101]
We're using 

```ruby
gem "validate_url", "~> 1.0"
```

in our Gemfile but when I try (both in test and development mode) to require `rspec_matcher` as indicated in the `README` I get the following `LoadError`:

```ruby
[4] pry(main)> require "validate_url"
=> false
[5] pry(main)> require "validate_url/rspec_matcher"
LoadError: cannot load such file -- validate_url/rspec_matcher
from /Users/rhymes/.gem/ruby/2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
Caused by Bootsnap::LoadPathCache::FallbackScan:
from
```

I also tried with `irb`:

```ruby
irb(main):001:0> require "validate_url"
=> true
irb(main):002:0> require "validate_url/rspec_matcher"
Traceback (most recent call last):
        6: from /Users/rhymes/.rubies/ruby-2.7.1/bin/irb:23:in `<main>'
        5: from /Users/rhymes/.rubies/ruby-2.7.1/bin/irb:23:in `load'
        4: from /Users/rhymes/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        3: from (irb):2
        2: from /Users/rhymes/.rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
        1: from /Users/rhymes/.rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:155:in `require'
LoadError (cannot load such file -- validate_url/rspec_matcher)
```

any ideas?

**Comment by Liquidsoul** [comment]
Hi @rhymes 

Seems like I stumbled on the same problem while integrating this gem.

It appears that the latest version of the code was not released to RubyGem.
In the released version (which is one year old), you can access the matcher using just `require 'rspec_matcher'`. But this may not be a good thing because this could conflict with some of your other gems (now or in the future).

What you could do is bundle the latest version of the code using a git reference like this in your Gemfile:
```
gem 'validate_url', git: 'https://github.com/perfectline/validates_url', ref: 'aae8b65e047c89afdaa2617b595eb181dccff6b0'
```

Hope this helps.

**Comment by rhymes** [comment]
Thanks, it works. 

Any plans on releasing this?

**Comment by kritik** [comment]
released new version, so can be closed

**Comment by rhymes** [comment]
Works perfectly, thank you!
